name: CI

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Validate Terraform files
      run: |
        make validate-oracle
        make validate-google
